# Generated by Django 5.1.3 on 2025-02-10 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcClass",
            fields=[
                ("class_id", models.AutoField(primary_key=True, serialize=False)),
                ("class_name", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "ac_class",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Accounts2022155006",
            fields=[
                (
                    "loanno",
                    models.IntegerField(
                        db_column="LOANNO", primary_key=True, serialize=False
                    ),
                ),
                (
                    "empno",
                    models.DecimalField(
                        blank=True,
                        db_column="EMPNO",
                        decimal_places=0,
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, db_column="TYPE", max_length=1, null=True
                    ),
                ),
                (
                    "amnt",
                    models.DecimalField(
                        blank=True,
                        db_column="AMNT",
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "accounts2022155006",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AcReq",
            fields=[
                ("req_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_req", models.TextField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "ac_req",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("ac_id", models.AutoField(primary_key=True, serialize=False)),
                ("ac_time", models.DateTimeField(blank=True, null=True)),
                ("ac_place", models.TextField(blank=True, null=True)),
                ("ac_pe", models.IntegerField(blank=True, null=True)),
                ("ac_require", models.TextField(blank=True, null=True)),
                ("acdesc", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "activity",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AddActivity",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("ac_time", models.DateTimeField(blank=True, null=True)),
                ("ac_pe", models.IntegerField(blank=True, null=True)),
                ("ac_require", models.TextField(blank=True, null=True)),
                ("modifytime", models.DateTimeField(blank=True, null=True)),
                ("acdesc", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "add_activity",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Administrator",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "administrator",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Dept2022155006",
            fields=[
                (
                    "deptno",
                    models.IntegerField(
                        db_column="DEPTNO", primary_key=True, serialize=False
                    ),
                ),
                (
                    "dname",
                    models.CharField(
                        blank=True, db_column="DNAME", max_length=15, null=True
                    ),
                ),
                (
                    "loc",
                    models.CharField(
                        blank=True, db_column="LOC", max_length=15, null=True
                    ),
                ),
            ],
            options={
                "db_table": "dept2022155006",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Emp2022155006",
            fields=[
                (
                    "empno",
                    models.IntegerField(
                        db_column="EMPNO", primary_key=True, serialize=False
                    ),
                ),
                (
                    "ename",
                    models.CharField(
                        blank=True, db_column="ENAME", max_length=10, null=True
                    ),
                ),
                (
                    "job",
                    models.CharField(
                        blank=True, db_column="JOB", max_length=15, null=True
                    ),
                ),
                ("mgr", models.IntegerField(blank=True, db_column="MGR", null=True)),
                (
                    "hiredate",
                    models.DateField(blank=True, db_column="HIREDATE", null=True),
                ),
                ("sal", models.IntegerField(blank=True, db_column="SAL", null=True)),
                ("comm", models.IntegerField(blank=True, db_column="COMM", null=True)),
            ],
            options={
                "db_table": "emp2022155006",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ExamReq",
            fields=[
                ("exam_id", models.IntegerField(primary_key=True, serialize=False)),
                ("exam_date", models.DateTimeField(blank=True, null=True)),
                ("exam_exp", models.TextField(blank=True, null=True)),
                ("is_req", models.TextField(blank=True, null=True)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "exam_req",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NormalUser",
            fields=[
                ("normal_user_id", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("user_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "normal_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReqActivity",
            fields=[
                (
                    "normal_user_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "req_activity",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ShenheRecord",
            fields=[
                ("exam_id", models.AutoField(primary_key=True, serialize=False)),
                ("req_id", models.IntegerField(blank=True, null=True)),
                ("exam_date", models.DateTimeField(blank=True, null=True)),
                ("exam_exp", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "shenhe_record",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SysConfig",
            fields=[
                (
                    "variable",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("value", models.CharField(blank=True, max_length=128, null=True)),
                ("set_time", models.DateTimeField(blank=True, null=True)),
                ("set_by", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "sys_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UsersReq",
            fields=[
                (
                    "normal_user_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("ac_id", models.IntegerField(blank=True, null=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("is_req", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "users_req",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("user_name", models.CharField(blank=True, max_length=255, null=True)),
                ("role", models.TextField(blank=True, null=True)),
                ("last_login", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "users",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ActivityEdit",
            fields=[
                (
                    "ac",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="app.activity",
                    ),
                ),
                ("admin_id", models.IntegerField()),
                ("ac_time", models.DateTimeField(blank=True, null=True)),
                ("ac_pe", models.IntegerField(blank=True, null=True)),
                ("ac_require", models.TextField(blank=True, null=True)),
                ("modifytime", models.DateTimeField(blank=True, null=True)),
                ("acdesc", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "activity_edit",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DelActivety",
            fields=[
                (
                    "ac",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="app.activity",
                    ),
                ),
                ("admin_id", models.IntegerField()),
                ("deletime", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "del_activety",
                "managed": False,
            },
        ),
    ]
