# Generated by Django 5.1.3 on 2025-02-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
